dist: xenial
language: rust
rust:
- nightly
cache: cargo
before_install:
- wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
- sudo dpkg -i packages-microsoft-prod.deb
- sudo apt-get install apt-transport-https
- sudo apt-get update
- sudo apt-get install dotnet-sdk-2.2
- cp src/config.sample.rs src/config.rs
env:
  global:
    secure: bu10BMtQcAUMdHgLLUUSC4VogeNmgCH3ohgf+wj7qzFQ7xmkq+8YJVv/3/mWteOGhdaV2naz/mSTWPNiwbw141PvXdHnfPES5cheREeajqooRzik60KlGLqQUWtZioMjG7PLTEv1DdGnoIHWeXn1TYy/oxEqtIo7hK9z3YEoU5zuAEdbgNtmP4d2EFPNRfLzrlgx2c1qA52FuCnZYVD/2Ch//XCXfGdomBI1uLyoId6Rnq8i9wDalx2++kqeDaeZsUESwi92v60jV7koAa9Y9hpBBanaZ057hnLUGhAXIYIcaK+jQYwiR/IMLsJq2ASTXpI5IKZZ2veuhMPgoDeuQYclEVlpFzgeYV0wtrvonHzJzq1ylo/po7f8rg1cjP7RdRdxjj8glbKXUHLMVwFhnh6vZBl5wA7iiRL/SD0OjwKld8SdL75Rbw5p6xLXVVHjHJ5SSoD7ZrlrRnFJfvz0V/XB1UlDPaGPZN+Tv4x3RxRxRvHzn+cnvpmQXnRRHIiBXKoKQ5w7Y5RbglLMJUzIf4jfi/8E+CZVjt64+j3ysFq+Q2xG6tJMruDxZP5QvlJRdLxgdGwNr/hjckBox/zlHV8j/D0CAu3i5XZOcQrdvbjXWqosNox8p1Au2gDLVfHc0LY/O5Kiqmt5PdSjbMg/rGWZ0Ctjid4vwGrkdJgv6wI=
